/**
 * Supabase auth emails, rendered through the same layout as purchase receipts.
 *
 * These are not sent from the app. `pnpm email:templates` writes them to
 * `supabase/templates/*.html`, where the Supabase CLI picks them up via
 * `[auth.email.template.*]` in `supabase/config.toml`. GoTrue substitutes the
 * `{{ . }}` placeholders when it sends.
 *
 * Only the two emails this app actually triggers live here: signup
 * confirmation (`sign-up-form.tsx`) and password recovery
 * (`forgot-password-form.tsx`).
 *
 * Imports must stay relative — the generator runs under plain Node, which does
 * not resolve the `@/*` alias.
 */

import { ctaButton, renderEmailLayout } from "./layout.ts";

/**
 * `{{ .ConfirmationURL }}` rather than `{{ .TokenHash }}` on purpose: it
 * honours the `emailRedirectTo` each form sets, so confirmation links reach
 * `/auth/callback`, which creates the `user_info` profile row. A token-hash
 * link would land on `/auth/confirm`, which establishes the session but never
 * creates that row.
 */
const CONFIRMATION_URL = "{{ .ConfirmationURL }}";

function fallbackLink() {
  return `<p style="margin:0 0 8px;font-size:13px;line-height:1.5;color:#6b7280;">
    If the button doesn’t work, paste this link into your browser:
  </p>
  <p style="margin:0 0 24px;font-size:13px;line-height:1.5;word-break:break-all;">
    <a href="${CONFIRMATION_URL}" style="color:#4b5563;">${CONFIRMATION_URL}</a>
  </p>`;
}

function note(text: string) {
  return `<p style="margin:0;font-size:13px;line-height:1.5;color:#6b7280;">${text}</p>`;
}

export function renderConfirmationEmail() {
  return renderEmailLayout({
    heading: "Confirm your email",
    intro:
      "Thanks for signing up for UX Hub. Confirm your email address to finish creating your account.",
    body: [
      ctaButton({ label: "Confirm email address", url: CONFIRMATION_URL }),
      fallbackLink(),
      note("If you didn’t create a UX Hub account, you can ignore this email."),
    ].join("\n"),
  });
}

export function renderRecoveryEmail() {
  return renderEmailLayout({
    heading: "Reset your password",
    intro:
      "We received a request to reset the password for your UX Hub account. Choose a new one below.",
    body: [
      ctaButton({ label: "Choose a new password", url: CONFIRMATION_URL }),
      fallbackLink(),
      note(
        "If you didn’t request a password reset, you can ignore this email — your password will stay the same."
      ),
    ].join("\n"),
  });
}

/** Filename in `supabase/templates` -> rendered HTML. */
export const AUTH_EMAIL_TEMPLATES = {
  "confirmation.html": renderConfirmationEmail,
  "recovery.html": renderRecoveryEmail,
} as const;

/** Header stamped onto every generated file so nobody edits the output. */
export const GENERATED_BANNER = `<!--
  Generated by \`pnpm email:templates\` from src/lib/email/auth-templates.ts.
  Edit that file and regenerate — changes made here are overwritten.
-->`;
