import type { TeamMember } from "@/features/marketing/types";

export const TEAM_MEMBERS: TeamMember[] = [
  {
    name: "Aurora Cheng",
    role: "Co-President",
    image: "/people/aurora.png",
    roleEmoji: "⭐",
  },
  {
    name: "Elisabeth Lau",
    role: "Co-President",
    image: "/people/Elisabeth.png",
    roleEmoji: "⭐",
  },
  {
    name: "Aubrey Ventura",
    role: "VP Design",
    image: "/people/aubrey.png",
    roleEmoji: "🎨",
  },
  {
    name: "Cherry Wang",
    role: "VP Marketing",
    image: "/people/cherry.jpg",
    roleEmoji: "🎬",
  },
  {
    name: "Taro Ren",
    role: "VP Internal",
    image: "/people/taro.jpeg",
    roleEmoji: "🎉",
  },
  {
    name: "Brian Yang",
    role: "Co-Treasurer",
    image: "/people/brian.png",
    roleEmoji: "💵",
  },
  {
    name: "Carys Fong",
    role: "Co-VP Logistics",
    image: "/people/carys.png",
    roleEmoji: "💡",
  },
  {
    name: "Eric Yan",
    role: "Co-VP Logistics",
    image: "/people/eric.png",
    roleEmoji: "💡",
  },
  {
    name: "Jessie Megan",
    role: "Co-VP Partnerships",
    image: "/people/jessie.png",
    roleEmoji: "🤝",
  },
  {
    name: "Quang Mai",
    role: "Co-VP Partnerships",
    image: "/people/quang.jpg",
    roleEmoji: "🤝",
  },
  {
    name: "Elaine Li",
    role: "Advisor",
    image: "/people/elaine.jpg",
    roleEmoji: "💭",
  },
  {
    name: "Erin Chiu",
    role: "Advisor",
    image: "/people/erin.png",
    roleEmoji: "💭",
  },
  {
    name: "Owen Li",
    role: "Advisor",
    image: "/people/owen.jpg",
    roleEmoji: "💭",
  },
  {
    name: "Iris Chan",
    role: "Design Director",
    image: "/people/iris-chan.jpg",
    roleEmoji: "🎨",
  },
  {
    name: "Sukhraj Chane",
    role: "Design Director & Developer",
    image: "/people/sukhraj.jpg",
    roleEmoji: "🎨",
  },
  {
    name: "Ellen Chu",
    role: "Marketing Director",
    image: "/people/ellen.jpg",
    roleEmoji: "🎬",
  },
  {
    name: "Kelly Wei Jin",
    role: "Marketing Director",
    image: "/people/kelly.jpg",
    roleEmoji: "🎬",
  },
  {
    name: "Iris-Danna Liu",
    role: "Marketing Director",
    image: "/people/iris-danna.jpg",
    roleEmoji: "🎬",
  },
  {
    name: "Justin Pilson",
    role: "Marketing Director",
    image: "/people/justin.jpg",
    roleEmoji: "🎬",
  },
  {
    name: "Avia Wen",
    role: "Logistics Director",
    image: "/people/avia.jpg",
    roleEmoji: "💡",
  },
  {
    name: "Delia Zhang",
    role: "Logistics Director",
    image: "/people/delia.jpg",
    roleEmoji: "💡",
  },
  {
    name: "Jason Zhang",
    role: "Logistics Director",
    image: "/people/jason.jpg",
    roleEmoji: "💡",
  },
  {
    name: "Lucy Zhu",
    role: "Logistics Director",
    image: "/people/lucy.jpg",
    roleEmoji: "💡",
  },
  {
    name: "Mia Makino",
    role: "Logistics Director",
    image: "/people/Mia.png",
    roleEmoji: "💡",
  },
  {
    name: "Brady Spur",
    role: "Partnerships Director",
    image: "/people/brady.jpg",
    roleEmoji: "🤝",
  },
  {
    name: "David Theopine",
    role: "Partnerships Director",
    image: "/people/david.png",
    roleEmoji: "🤝",
  },
  {
    name: "Katrina Wei",
    role: "Partnerships Director",
    image: "/people/Kat.png",
    roleEmoji: "🤝",
  },
  {
    name: "Rin Hatanaka",
    role: "Partnerships Director",
    image: "/people/rin.jpg",
    roleEmoji: "🤝",
  },
  {
    name: "Jefferson Abraham",
    role: "Developer",
    image: "/people/jefferson.jpg",
    roleEmoji: "💻",
  },
  {
    name: "Johnny Dong",
    role: "Developer",
    image: "/people/johnny.png",
    roleEmoji: "💻",
  },
];
